// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: werewolf_2.proto

package werewolf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 游戏阶段（细分）
type Phase int32

const (
	Phase_PHASE_WAITING        Phase = 0
	Phase_PHASE_NIGHT_GUARD    Phase = 1 // 守卫行动
	Phase_PHASE_NIGHT_WEREWOLF Phase = 2 // 狼人行动
	Phase_PHASE_NIGHT_WITCH    Phase = 3 // 女巫行动
	Phase_PHASE_NIGHT_SEER     Phase = 4 // 预言家行动
	Phase_PHASE_DAY_DISCUSSION Phase = 5 // 白天讨论
	Phase_PHASE_DAY_VOTING     Phase = 6 // 投票
	Phase_PHASE_DAY_LAST_WORDS Phase = 7 // 遗言
	Phase_PHASE_GAME_OVER      Phase = 8 // 游戏结束
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_WAITING",
		1: "PHASE_NIGHT_GUARD",
		2: "PHASE_NIGHT_WEREWOLF",
		3: "PHASE_NIGHT_WITCH",
		4: "PHASE_NIGHT_SEER",
		5: "PHASE_DAY_DISCUSSION",
		6: "PHASE_DAY_VOTING",
		7: "PHASE_DAY_LAST_WORDS",
		8: "PHASE_GAME_OVER",
	}
	Phase_value = map[string]int32{
		"PHASE_WAITING":        0,
		"PHASE_NIGHT_GUARD":    1,
		"PHASE_NIGHT_WEREWOLF": 2,
		"PHASE_NIGHT_WITCH":    3,
		"PHASE_NIGHT_SEER":     4,
		"PHASE_DAY_DISCUSSION": 5,
		"PHASE_DAY_VOTING":     6,
		"PHASE_DAY_LAST_WORDS": 7,
		"PHASE_GAME_OVER":      8,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_werewolf_2_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_werewolf_2_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{0}
}

// 游戏状态
type GameState int32

const (
	GameState_WAITING  GameState = 0
	GameState_NIGHT    GameState = 1
	GameState_DAY      GameState = 2
	GameState_FINISHED GameState = 3
)

// Enum value maps for GameState.
var (
	GameState_name = map[int32]string{
		0: "WAITING",
		1: "NIGHT",
		2: "DAY",
		3: "FINISHED",
	}
	GameState_value = map[string]int32{
		"WAITING":  0,
		"NIGHT":    1,
		"DAY":      2,
		"FINISHED": 3,
	}
)

func (x GameState) Enum() *GameState {
	p := new(GameState)
	*p = x
	return p
}

func (x GameState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameState) Descriptor() protoreflect.EnumDescriptor {
	return file_werewolf_2_proto_enumTypes[1].Descriptor()
}

func (GameState) Type() protoreflect.EnumType {
	return &file_werewolf_2_proto_enumTypes[1]
}

func (x GameState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameState.Descriptor instead.
func (GameState) EnumDescriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{1}
}

// 玩家角色
type Role int32

const (
	Role_UNKNOWN  Role = 0
	Role_WEREWOLF Role = 1
	Role_VILLAGER Role = 2
	Role_SEER     Role = 3
	Role_WITCH    Role = 4
	Role_HUNTER   Role = 5
	Role_GUARD    Role = 6
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "UNKNOWN",
		1: "WEREWOLF",
		2: "VILLAGER",
		3: "SEER",
		4: "WITCH",
		5: "HUNTER",
		6: "GUARD",
	}
	Role_value = map[string]int32{
		"UNKNOWN":  0,
		"WEREWOLF": 1,
		"VILLAGER": 2,
		"SEER":     3,
		"WITCH":    4,
		"HUNTER":   5,
		"GUARD":    6,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_werewolf_2_proto_enumTypes[2].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_werewolf_2_proto_enumTypes[2]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{2}
}

// 阵营
type Camp int32

const (
	Camp_CAMP_UNKNOWN  Camp = 0
	Camp_CAMP_WEREWOLF Camp = 1 // 狼人阵营
	Camp_CAMP_VILLAGER Camp = 2 // 好人阵营
)

// Enum value maps for Camp.
var (
	Camp_name = map[int32]string{
		0: "CAMP_UNKNOWN",
		1: "CAMP_WEREWOLF",
		2: "CAMP_VILLAGER",
	}
	Camp_value = map[string]int32{
		"CAMP_UNKNOWN":  0,
		"CAMP_WEREWOLF": 1,
		"CAMP_VILLAGER": 2,
	}
)

func (x Camp) Enum() *Camp {
	p := new(Camp)
	*p = x
	return p
}

func (x Camp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Camp) Descriptor() protoreflect.EnumDescriptor {
	return file_werewolf_2_proto_enumTypes[3].Descriptor()
}

func (Camp) Type() protoreflect.EnumType {
	return &file_werewolf_2_proto_enumTypes[3]
}

func (x Camp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Camp.Descriptor instead.
func (Camp) EnumDescriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{3}
}

type GameEvent_EventType int32

const (
	GameEvent_EVENT_UNKNOWN          GameEvent_EventType = 0
	GameEvent_EVENT_PLAYER_JOINED    GameEvent_EventType = 1
	GameEvent_EVENT_GAME_STARTED     GameEvent_EventType = 2
	GameEvent_EVENT_PHASE_CHANGED    GameEvent_EventType = 3
	GameEvent_EVENT_PLAYER_DIED      GameEvent_EventType = 4
	GameEvent_EVENT_ACTION_COMPLETED GameEvent_EventType = 5
	GameEvent_EVENT_GAME_OVER        GameEvent_EventType = 6
	GameEvent_EVENT_YOUR_TURN        GameEvent_EventType = 7 // 轮到你行动
)

// Enum value maps for GameEvent_EventType.
var (
	GameEvent_EventType_name = map[int32]string{
		0: "EVENT_UNKNOWN",
		1: "EVENT_PLAYER_JOINED",
		2: "EVENT_GAME_STARTED",
		3: "EVENT_PHASE_CHANGED",
		4: "EVENT_PLAYER_DIED",
		5: "EVENT_ACTION_COMPLETED",
		6: "EVENT_GAME_OVER",
		7: "EVENT_YOUR_TURN",
	}
	GameEvent_EventType_value = map[string]int32{
		"EVENT_UNKNOWN":          0,
		"EVENT_PLAYER_JOINED":    1,
		"EVENT_GAME_STARTED":     2,
		"EVENT_PHASE_CHANGED":    3,
		"EVENT_PLAYER_DIED":      4,
		"EVENT_ACTION_COMPLETED": 5,
		"EVENT_GAME_OVER":        6,
		"EVENT_YOUR_TURN":        7,
	}
)

func (x GameEvent_EventType) Enum() *GameEvent_EventType {
	p := new(GameEvent_EventType)
	*p = x
	return p
}

func (x GameEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_werewolf_2_proto_enumTypes[4].Descriptor()
}

func (GameEvent_EventType) Type() protoreflect.EnumType {
	return &file_werewolf_2_proto_enumTypes[4]
}

func (x GameEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameEvent_EventType.Descriptor instead.
func (GameEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{15, 0}
}

// 玩家信息
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=werewolf.Role" json:"role,omitempty"`
	Camp          Camp                   `protobuf:"varint,4,opt,name=camp,proto3,enum=werewolf.Camp" json:"camp,omitempty"`
	IsAlive       bool                   `protobuf:"varint,5,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	Position      int32                  `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	CanAct        bool                   `protobuf:"varint,7,opt,name=can_act,json=canAct,proto3" json:"can_act,omitempty"` // 当前是否可以行动
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_werewolf_2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_UNKNOWN
}

func (x *Player) GetCamp() Camp {
	if x != nil {
		return x.Camp
	}
	return Camp_CAMP_UNKNOWN
}

func (x *Player) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Player) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Player) GetCanAct() bool {
	if x != nil {
		return x.CanAct
	}
	return false
}

// 夜晚行动记录
type NightAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=werewolf.Role" json:"role,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NightAction) Reset() {
	*x = NightAction{}
	mi := &file_werewolf_2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NightAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NightAction) ProtoMessage() {}

func (x *NightAction) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NightAction.ProtoReflect.Descriptor instead.
func (*NightAction) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{1}
}

func (x *NightAction) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *NightAction) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_UNKNOWN
}

func (x *NightAction) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NightAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *NightAction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 阶段信息
type PhaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPhase  Phase                  `protobuf:"varint,1,opt,name=current_phase,json=currentPhase,proto3,enum=werewolf.Phase" json:"current_phase,omitempty"`
	PhaseName     string                 `protobuf:"bytes,2,opt,name=phase_name,json=phaseName,proto3" json:"phase_name,omitempty"`
	ActiveRoles   []string               `protobuf:"bytes,3,rep,name=active_roles,json=activeRoles,proto3" json:"active_roles,omitempty"` // 当前阶段活跃的角色
	TimeLimit     int32                  `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`      // 阶段时间限制（秒）
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseInfo) Reset() {
	*x = PhaseInfo{}
	mi := &file_werewolf_2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseInfo) ProtoMessage() {}

func (x *PhaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseInfo.ProtoReflect.Descriptor instead.
func (*PhaseInfo) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{2}
}

func (x *PhaseInfo) GetCurrentPhase() Phase {
	if x != nil {
		return x.CurrentPhase
	}
	return Phase_PHASE_WAITING
}

func (x *PhaseInfo) GetPhaseName() string {
	if x != nil {
		return x.PhaseName
	}
	return ""
}

func (x *PhaseInfo) GetActiveRoles() []string {
	if x != nil {
		return x.ActiveRoles
	}
	return nil
}

func (x *PhaseInfo) GetTimeLimit() int32 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

func (x *PhaseInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 创建游戏房间请求
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,2,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	RoleConfig    map[string]int32       `protobuf:"bytes,3,rep,name=role_config,json=roleConfig,proto3" json:"role_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_werewolf_2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *CreateRoomRequest) GetRoleConfig() map[string]int32 {
	if x != nil {
		return x.RoleConfig
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_werewolf_2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 加入房间请求
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_werewolf_2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Player        *Player                `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_werewolf_2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinRoomResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

// 开始游戏请求
type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_werewolf_2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{7}
}

func (x *StartGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type StartGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PhaseInfo     *PhaseInfo             `protobuf:"bytes,3,opt,name=phase_info,json=phaseInfo,proto3" json:"phase_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameResponse) Reset() {
	*x = StartGameResponse{}
	mi := &file_werewolf_2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameResponse) ProtoMessage() {}

func (x *StartGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameResponse.ProtoReflect.Descriptor instead.
func (*StartGameResponse) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{8}
}

func (x *StartGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartGameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartGameResponse) GetPhaseInfo() *PhaseInfo {
	if x != nil {
		return x.PhaseInfo
	}
	return nil
}

// 夜晚行动请求
type NightActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId       string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TargetPlayerId string                 `protobuf:"bytes,3,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	ActionType     string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NightActionRequest) Reset() {
	*x = NightActionRequest{}
	mi := &file_werewolf_2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NightActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NightActionRequest) ProtoMessage() {}

func (x *NightActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NightActionRequest.ProtoReflect.Descriptor instead.
func (*NightActionRequest) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{9}
}

func (x *NightActionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NightActionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *NightActionRequest) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *NightActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

type NightActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NightActionResponse) Reset() {
	*x = NightActionResponse{}
	mi := &file_werewolf_2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NightActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NightActionResponse) ProtoMessage() {}

func (x *NightActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NightActionResponse.ProtoReflect.Descriptor instead.
func (*NightActionResponse) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{10}
}

func (x *NightActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NightActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NightActionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// 投票请求
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	VoterId       string                 `protobuf:"bytes,2,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_werewolf_2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{11}
}

func (x *VoteRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *VoteRequest) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

func (x *VoteRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_werewolf_2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{12}
}

func (x *VoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取游戏状态请求
type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_werewolf_2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{13}
}

func (x *GetGameStateRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetGameStateRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	State         GameState              `protobuf:"varint,2,opt,name=state,proto3,enum=werewolf.GameState" json:"state,omitempty"`
	PhaseInfo     *PhaseInfo             `protobuf:"bytes,3,opt,name=phase_info,json=phaseInfo,proto3" json:"phase_info,omitempty"`
	Players       []*Player              `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	DayCount      int32                  `protobuf:"varint,5,opt,name=day_count,json=dayCount,proto3" json:"day_count,omitempty"`
	CurrentPlayer *Player                `protobuf:"bytes,6,opt,name=current_player,json=currentPlayer,proto3" json:"current_player,omitempty"` // 当前玩家的完整信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_werewolf_2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{14}
}

func (x *GetGameStateResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetGameStateResponse) GetState() GameState {
	if x != nil {
		return x.State
	}
	return GameState_WAITING
}

func (x *GetGameStateResponse) GetPhaseInfo() *PhaseInfo {
	if x != nil {
		return x.PhaseInfo
	}
	return nil
}

func (x *GetGameStateResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GetGameStateResponse) GetDayCount() int32 {
	if x != nil {
		return x.DayCount
	}
	return 0
}

func (x *GetGameStateResponse) GetCurrentPlayer() *Player {
	if x != nil {
		return x.CurrentPlayer
	}
	return nil
}

// 游戏事件
type GameEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventType       GameEvent_EventType    `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=werewolf.GameEvent_EventType" json:"event_type,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PhaseInfo       *PhaseInfo             `protobuf:"bytes,3,opt,name=phase_info,json=phaseInfo,proto3" json:"phase_info,omitempty"`
	AffectedPlayers []*Player              `protobuf:"bytes,4,rep,name=affected_players,json=affectedPlayers,proto3" json:"affected_players,omitempty"`
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData       map[string]string      `protobuf:"bytes,6,rep,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_werewolf_2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_werewolf_2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_werewolf_2_proto_rawDescGZIP(), []int{15}
}

func (x *GameEvent) GetEventType() GameEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return GameEvent_EVENT_UNKNOWN
}

func (x *GameEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameEvent) GetPhaseInfo() *PhaseInfo {
	if x != nil {
		return x.PhaseInfo
	}
	return nil
}

func (x *GameEvent) GetAffectedPlayers() []*Player {
	if x != nil {
		return x.AffectedPlayers
	}
	return nil
}

func (x *GameEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GameEvent) GetExtraData() map[string]string {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

var File_werewolf_2_proto protoreflect.FileDescriptor

const file_werewolf_2_proto_rawDesc = "" +
	"\n" +
	"\x10werewolf_2.proto\x12\bwerewolf\"\xd1\x01\n" +
	"\x06Player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0e.werewolf.RoleR\x04role\x12\"\n" +
	"\x04camp\x18\x04 \x01(\x0e2\x0e.werewolf.CampR\x04camp\x12\x19\n" +
	"\bis_alive\x18\x05 \x01(\bR\aisAlive\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12\x17\n" +
	"\acan_act\x18\a \x01(\bR\x06canAct\"\xaa\x01\n" +
	"\vNightAction\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\"\n" +
	"\x04role\x18\x02 \x01(\x0e2\x0e.werewolf.RoleR\x04role\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xc4\x01\n" +
	"\tPhaseInfo\x124\n" +
	"\rcurrent_phase\x18\x01 \x01(\x0e2\x0f.werewolf.PhaseR\fcurrentPhase\x12\x1d\n" +
	"\n" +
	"phase_name\x18\x02 \x01(\tR\tphaseName\x12!\n" +
	"\factive_roles\x18\x03 \x03(\tR\vactiveRoles\x12\x1d\n" +
	"\n" +
	"time_limit\x18\x04 \x01(\x05R\ttimeLimit\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xde\x01\n" +
	"\x11CreateRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1f\n" +
	"\vmax_players\x18\x02 \x01(\x05R\n" +
	"maxPlayers\x12L\n" +
	"\vrole_config\x18\x03 \x03(\v2+.werewolf.CreateRoomRequest.RoleConfigEntryR\n" +
	"roleConfig\x1a=\n" +
	"\x0fRoleConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"G\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"h\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\"p\n" +
	"\x10JoinRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x06player\x18\x03 \x01(\v2\x10.werewolf.PlayerR\x06player\"+\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"{\n" +
	"\x11StartGameResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\n" +
	"phase_info\x18\x03 \x01(\v2\x13.werewolf.PhaseInfoR\tphaseInfo\"\x95\x01\n" +
	"\x12NightActionRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12(\n" +
	"\x10target_player_id\x18\x03 \x01(\tR\x0etargetPlayerId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\"a\n" +
	"\x13NightActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\"^\n" +
	"\vVoteRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bvoter_id\x18\x02 \x01(\tR\avoterId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"B\n" +
	"\fVoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x13GetGameStateRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x90\x02\n" +
	"\x14GetGameStateResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.werewolf.GameStateR\x05state\x122\n" +
	"\n" +
	"phase_info\x18\x03 \x01(\v2\x13.werewolf.PhaseInfoR\tphaseInfo\x12*\n" +
	"\aplayers\x18\x04 \x03(\v2\x10.werewolf.PlayerR\aplayers\x12\x1b\n" +
	"\tday_count\x18\x05 \x01(\x05R\bdayCount\x127\n" +
	"\x0ecurrent_player\x18\x06 \x01(\v2\x10.werewolf.PlayerR\rcurrentPlayer\"\xbb\x04\n" +
	"\tGameEvent\x12<\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1d.werewolf.GameEvent.EventTypeR\teventType\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\n" +
	"phase_info\x18\x03 \x01(\v2\x13.werewolf.PhaseInfoR\tphaseInfo\x12;\n" +
	"\x10affected_players\x18\x04 \x03(\v2\x10.werewolf.PlayerR\x0faffectedPlayers\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12A\n" +
	"\n" +
	"extra_data\x18\x06 \x03(\v2\".werewolf.GameEvent.ExtraDataEntryR\textraData\x1a<\n" +
	"\x0eExtraDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x01\n" +
	"\tEventType\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13EVENT_PLAYER_JOINED\x10\x01\x12\x16\n" +
	"\x12EVENT_GAME_STARTED\x10\x02\x12\x17\n" +
	"\x13EVENT_PHASE_CHANGED\x10\x03\x12\x15\n" +
	"\x11EVENT_PLAYER_DIED\x10\x04\x12\x1a\n" +
	"\x16EVENT_ACTION_COMPLETED\x10\x05\x12\x13\n" +
	"\x0fEVENT_GAME_OVER\x10\x06\x12\x13\n" +
	"\x0fEVENT_YOUR_TURN\x10\a*\xd7\x01\n" +
	"\x05Phase\x12\x11\n" +
	"\rPHASE_WAITING\x10\x00\x12\x15\n" +
	"\x11PHASE_NIGHT_GUARD\x10\x01\x12\x18\n" +
	"\x14PHASE_NIGHT_WEREWOLF\x10\x02\x12\x15\n" +
	"\x11PHASE_NIGHT_WITCH\x10\x03\x12\x14\n" +
	"\x10PHASE_NIGHT_SEER\x10\x04\x12\x18\n" +
	"\x14PHASE_DAY_DISCUSSION\x10\x05\x12\x14\n" +
	"\x10PHASE_DAY_VOTING\x10\x06\x12\x18\n" +
	"\x14PHASE_DAY_LAST_WORDS\x10\a\x12\x13\n" +
	"\x0fPHASE_GAME_OVER\x10\b*:\n" +
	"\tGameState\x12\v\n" +
	"\aWAITING\x10\x00\x12\t\n" +
	"\x05NIGHT\x10\x01\x12\a\n" +
	"\x03DAY\x10\x02\x12\f\n" +
	"\bFINISHED\x10\x03*[\n" +
	"\x04Role\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bWEREWOLF\x10\x01\x12\f\n" +
	"\bVILLAGER\x10\x02\x12\b\n" +
	"\x04SEER\x10\x03\x12\t\n" +
	"\x05WITCH\x10\x04\x12\n" +
	"\n" +
	"\x06HUNTER\x10\x05\x12\t\n" +
	"\x05GUARD\x10\x06*>\n" +
	"\x04Camp\x12\x10\n" +
	"\fCAMP_UNKNOWN\x10\x00\x12\x11\n" +
	"\rCAMP_WEREWOLF\x10\x01\x12\x11\n" +
	"\rCAMP_VILLAGER\x10\x022\x82\x04\n" +
	"\x0fWerewolfService\x12G\n" +
	"\n" +
	"CreateRoom\x12\x1b.werewolf.CreateRoomRequest\x1a\x1c.werewolf.CreateRoomResponse\x12A\n" +
	"\bJoinRoom\x12\x19.werewolf.JoinRoomRequest\x1a\x1a.werewolf.JoinRoomResponse\x12D\n" +
	"\tStartGame\x12\x1a.werewolf.StartGameRequest\x1a\x1b.werewolf.StartGameResponse\x12J\n" +
	"\vNightAction\x12\x1c.werewolf.NightActionRequest\x1a\x1d.werewolf.NightActionResponse\x125\n" +
	"\x04Vote\x12\x15.werewolf.VoteRequest\x1a\x16.werewolf.VoteResponse\x12M\n" +
	"\fGetGameState\x12\x1d.werewolf.GetGameStateRequest\x1a\x1e.werewolf.GetGameStateResponse\x12K\n" +
	"\x13SubscribeGameEvents\x12\x1d.werewolf.GetGameStateRequest\x1a\x13.werewolf.GameEvent0\x01B\x16Z\x14go_demo/pkg/werewolfb\x06proto3"

var (
	file_werewolf_2_proto_rawDescOnce sync.Once
	file_werewolf_2_proto_rawDescData []byte
)

func file_werewolf_2_proto_rawDescGZIP() []byte {
	file_werewolf_2_proto_rawDescOnce.Do(func() {
		file_werewolf_2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_werewolf_2_proto_rawDesc), len(file_werewolf_2_proto_rawDesc)))
	})
	return file_werewolf_2_proto_rawDescData
}

var file_werewolf_2_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_werewolf_2_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_werewolf_2_proto_goTypes = []any{
	(Phase)(0),                   // 0: werewolf.Phase
	(GameState)(0),               // 1: werewolf.GameState
	(Role)(0),                    // 2: werewolf.Role
	(Camp)(0),                    // 3: werewolf.Camp
	(GameEvent_EventType)(0),     // 4: werewolf.GameEvent.EventType
	(*Player)(nil),               // 5: werewolf.Player
	(*NightAction)(nil),          // 6: werewolf.NightAction
	(*PhaseInfo)(nil),            // 7: werewolf.PhaseInfo
	(*CreateRoomRequest)(nil),    // 8: werewolf.CreateRoomRequest
	(*CreateRoomResponse)(nil),   // 9: werewolf.CreateRoomResponse
	(*JoinRoomRequest)(nil),      // 10: werewolf.JoinRoomRequest
	(*JoinRoomResponse)(nil),     // 11: werewolf.JoinRoomResponse
	(*StartGameRequest)(nil),     // 12: werewolf.StartGameRequest
	(*StartGameResponse)(nil),    // 13: werewolf.StartGameResponse
	(*NightActionRequest)(nil),   // 14: werewolf.NightActionRequest
	(*NightActionResponse)(nil),  // 15: werewolf.NightActionResponse
	(*VoteRequest)(nil),          // 16: werewolf.VoteRequest
	(*VoteResponse)(nil),         // 17: werewolf.VoteResponse
	(*GetGameStateRequest)(nil),  // 18: werewolf.GetGameStateRequest
	(*GetGameStateResponse)(nil), // 19: werewolf.GetGameStateResponse
	(*GameEvent)(nil),            // 20: werewolf.GameEvent
	nil,                          // 21: werewolf.CreateRoomRequest.RoleConfigEntry
	nil,                          // 22: werewolf.GameEvent.ExtraDataEntry
}
var file_werewolf_2_proto_depIdxs = []int32{
	2,  // 0: werewolf.Player.role:type_name -> werewolf.Role
	3,  // 1: werewolf.Player.camp:type_name -> werewolf.Camp
	2,  // 2: werewolf.NightAction.role:type_name -> werewolf.Role
	0,  // 3: werewolf.PhaseInfo.current_phase:type_name -> werewolf.Phase
	21, // 4: werewolf.CreateRoomRequest.role_config:type_name -> werewolf.CreateRoomRequest.RoleConfigEntry
	5,  // 5: werewolf.JoinRoomResponse.player:type_name -> werewolf.Player
	7,  // 6: werewolf.StartGameResponse.phase_info:type_name -> werewolf.PhaseInfo
	1,  // 7: werewolf.GetGameStateResponse.state:type_name -> werewolf.GameState
	7,  // 8: werewolf.GetGameStateResponse.phase_info:type_name -> werewolf.PhaseInfo
	5,  // 9: werewolf.GetGameStateResponse.players:type_name -> werewolf.Player
	5,  // 10: werewolf.GetGameStateResponse.current_player:type_name -> werewolf.Player
	4,  // 11: werewolf.GameEvent.event_type:type_name -> werewolf.GameEvent.EventType
	7,  // 12: werewolf.GameEvent.phase_info:type_name -> werewolf.PhaseInfo
	5,  // 13: werewolf.GameEvent.affected_players:type_name -> werewolf.Player
	22, // 14: werewolf.GameEvent.extra_data:type_name -> werewolf.GameEvent.ExtraDataEntry
	8,  // 15: werewolf.WerewolfService.CreateRoom:input_type -> werewolf.CreateRoomRequest
	10, // 16: werewolf.WerewolfService.JoinRoom:input_type -> werewolf.JoinRoomRequest
	12, // 17: werewolf.WerewolfService.StartGame:input_type -> werewolf.StartGameRequest
	14, // 18: werewolf.WerewolfService.NightAction:input_type -> werewolf.NightActionRequest
	16, // 19: werewolf.WerewolfService.Vote:input_type -> werewolf.VoteRequest
	18, // 20: werewolf.WerewolfService.GetGameState:input_type -> werewolf.GetGameStateRequest
	18, // 21: werewolf.WerewolfService.SubscribeGameEvents:input_type -> werewolf.GetGameStateRequest
	9,  // 22: werewolf.WerewolfService.CreateRoom:output_type -> werewolf.CreateRoomResponse
	11, // 23: werewolf.WerewolfService.JoinRoom:output_type -> werewolf.JoinRoomResponse
	13, // 24: werewolf.WerewolfService.StartGame:output_type -> werewolf.StartGameResponse
	15, // 25: werewolf.WerewolfService.NightAction:output_type -> werewolf.NightActionResponse
	17, // 26: werewolf.WerewolfService.Vote:output_type -> werewolf.VoteResponse
	19, // 27: werewolf.WerewolfService.GetGameState:output_type -> werewolf.GetGameStateResponse
	20, // 28: werewolf.WerewolfService.SubscribeGameEvents:output_type -> werewolf.GameEvent
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_werewolf_2_proto_init() }
func file_werewolf_2_proto_init() {
	if File_werewolf_2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_werewolf_2_proto_rawDesc), len(file_werewolf_2_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_werewolf_2_proto_goTypes,
		DependencyIndexes: file_werewolf_2_proto_depIdxs,
		EnumInfos:         file_werewolf_2_proto_enumTypes,
		MessageInfos:      file_werewolf_2_proto_msgTypes,
	}.Build()
	File_werewolf_2_proto = out.File
	file_werewolf_2_proto_goTypes = nil
	file_werewolf_2_proto_depIdxs = nil
}
