// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: werewolf_2.proto

package werewolf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WerewolfService_CreateRoom_FullMethodName          = "/werewolf.WerewolfService/CreateRoom"
	WerewolfService_JoinRoom_FullMethodName            = "/werewolf.WerewolfService/JoinRoom"
	WerewolfService_StartGame_FullMethodName           = "/werewolf.WerewolfService/StartGame"
	WerewolfService_NightAction_FullMethodName         = "/werewolf.WerewolfService/NightAction"
	WerewolfService_Vote_FullMethodName                = "/werewolf.WerewolfService/Vote"
	WerewolfService_GetGameState_FullMethodName        = "/werewolf.WerewolfService/GetGameState"
	WerewolfService_SubscribeGameEvents_FullMethodName = "/werewolf.WerewolfService/SubscribeGameEvents"
)

// WerewolfServiceClient is the client API for WerewolfService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 狼人杀服务
type WerewolfServiceClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	NightAction(ctx context.Context, in *NightActionRequest, opts ...grpc.CallOption) (*NightActionResponse, error)
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error)
	SubscribeGameEvents(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error)
}

type werewolfServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWerewolfServiceClient(cc grpc.ClientConnInterface) WerewolfServiceClient {
	return &werewolfServiceClient{cc}
}

func (c *werewolfServiceClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, WerewolfService_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *werewolfServiceClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, WerewolfService_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *werewolfServiceClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, WerewolfService_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *werewolfServiceClient) NightAction(ctx context.Context, in *NightActionRequest, opts ...grpc.CallOption) (*NightActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NightActionResponse)
	err := c.cc.Invoke(ctx, WerewolfService_NightAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *werewolfServiceClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, WerewolfService_Vote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *werewolfServiceClient) GetGameState(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (*GetGameStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStateResponse)
	err := c.cc.Invoke(ctx, WerewolfService_GetGameState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *werewolfServiceClient) SubscribeGameEvents(ctx context.Context, in *GetGameStateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WerewolfService_ServiceDesc.Streams[0], WerewolfService_SubscribeGameEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetGameStateRequest, GameEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WerewolfService_SubscribeGameEventsClient = grpc.ServerStreamingClient[GameEvent]

// WerewolfServiceServer is the server API for WerewolfService service.
// All implementations must embed UnimplementedWerewolfServiceServer
// for forward compatibility.
//
// 狼人杀服务
type WerewolfServiceServer interface {
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	NightAction(context.Context, *NightActionRequest) (*NightActionResponse, error)
	Vote(context.Context, *VoteRequest) (*VoteResponse, error)
	GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error)
	SubscribeGameEvents(*GetGameStateRequest, grpc.ServerStreamingServer[GameEvent]) error
	mustEmbedUnimplementedWerewolfServiceServer()
}

// UnimplementedWerewolfServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWerewolfServiceServer struct{}

func (UnimplementedWerewolfServiceServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedWerewolfServiceServer) JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedWerewolfServiceServer) StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedWerewolfServiceServer) NightAction(context.Context, *NightActionRequest) (*NightActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NightAction not implemented")
}
func (UnimplementedWerewolfServiceServer) Vote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Vote not implemented")
}
func (UnimplementedWerewolfServiceServer) GetGameState(context.Context, *GetGameStateRequest) (*GetGameStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameState not implemented")
}
func (UnimplementedWerewolfServiceServer) SubscribeGameEvents(*GetGameStateRequest, grpc.ServerStreamingServer[GameEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeGameEvents not implemented")
}
func (UnimplementedWerewolfServiceServer) mustEmbedUnimplementedWerewolfServiceServer() {}
func (UnimplementedWerewolfServiceServer) testEmbeddedByValue()                         {}

// UnsafeWerewolfServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WerewolfServiceServer will
// result in compilation errors.
type UnsafeWerewolfServiceServer interface {
	mustEmbedUnimplementedWerewolfServiceServer()
}

func RegisterWerewolfServiceServer(s grpc.ServiceRegistrar, srv WerewolfServiceServer) {
	// If the following call panics, it indicates UnimplementedWerewolfServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WerewolfService_ServiceDesc, srv)
}

func _WerewolfService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerewolfServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WerewolfService_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerewolfServiceServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WerewolfService_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerewolfServiceServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WerewolfService_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerewolfServiceServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WerewolfService_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerewolfServiceServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WerewolfService_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerewolfServiceServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WerewolfService_NightAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NightActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerewolfServiceServer).NightAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WerewolfService_NightAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerewolfServiceServer).NightAction(ctx, req.(*NightActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WerewolfService_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerewolfServiceServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WerewolfService_Vote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerewolfServiceServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WerewolfService_GetGameState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerewolfServiceServer).GetGameState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WerewolfService_GetGameState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerewolfServiceServer).GetGameState(ctx, req.(*GetGameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WerewolfService_SubscribeGameEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetGameStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WerewolfServiceServer).SubscribeGameEvents(m, &grpc.GenericServerStream[GetGameStateRequest, GameEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WerewolfService_SubscribeGameEventsServer = grpc.ServerStreamingServer[GameEvent]

// WerewolfService_ServiceDesc is the grpc.ServiceDesc for WerewolfService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WerewolfService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "werewolf.WerewolfService",
	HandlerType: (*WerewolfServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _WerewolfService_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _WerewolfService_JoinRoom_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _WerewolfService_StartGame_Handler,
		},
		{
			MethodName: "NightAction",
			Handler:    _WerewolfService_NightAction_Handler,
		},
		{
			MethodName: "Vote",
			Handler:    _WerewolfService_Vote_Handler,
		},
		{
			MethodName: "GetGameState",
			Handler:    _WerewolfService_GetGameState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeGameEvents",
			Handler:       _WerewolfService_SubscribeGameEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "werewolf_2.proto",
}
